language: python
cache: pip
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install -U pip
  - pip install -U tox
  - pip install -U tox-travis
  - pip install -U coveralls
script:
  - tox -r

after_success:
  - coveralls

env:
  - TOXENV=django22
  - TOXENV=django30
matrix:
  exclude:
    - python: 3.5
      env: TOXENV=django30

notifications:
  email: false
sudo: false
